# preferenciasstreaming
CODIGO CRIADO EM PHP, QUANDO O CLIENTE ACESSA O SITE ELE É DIRECIONADO PARA UM FORMULARIO COM SEUS GOSTOS SEJA ELE FILMES, SERIES E MUSICASM ATRAVES DA BASE DE DADOS SERA SALVO, E TODA VEZ QUE O CLIENTE ACESSAR O STREAMING A PAGINA DE BOAS VINDAS, JÁ MOSTRARAO AS NOVIDADE DE ACORDO COM OS GOSTOS DO MESMO
